name: CI

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
    
  build-swiftpm:
    name: Build SwiftPM
    uses: oversizedev/GithubWorkflows/.github/workflows/build-swiftpm.yml@main
    with:
      package: "OversizeModels"
    secrets: inherit

  tests:
    name: Test
    needs: build-swiftpm
    uses: oversizedev/GithubWorkflows/.github/workflows/test.yml@main
    secrets: inherit

  bump:
     name: Bump version
     needs: tests
     uses: oversizedev/GithubWorkflows/.github/workflows/bump.yml@main
     secrets: inherit
